### ISSUE TITLE
Wrong type definition

### ISSUE THREAD

**Issue by belinde** [fattureincloud/fattureincloud-ts-sdk#14]
**Describe the bug**
`OAuth2AuthorizationCodeManager.fetchToken()` returns a `Promise<OAuth2AuthorizationCodeTokenResponse>`.
The class `OAuth2AuthorizationCodeTokenResponse` is said to have attributes in camelCase (tokenType, accessToken, refreshToken, expriresIn), but fetchToken returns instead a plain object in snake_case: 
```json
{
  "token_type":"'bearer",
  "access_token": "OMISSIS",
  "refresh_token": "OMISSIS",
  "expires_in": 86400
}
```

**Env info**
Please, provide us with the following details:
- Node 18.4.0
- TS SDK 2.0.4

**To Reproduce**
```typescript
import { OAuth2AuthorizationCodeManager, Scope } from '@fattureincloud/fattureincloud-ts-sdk';
import Conf from '../Conf';

const oauth = new OAuth2AuthorizationCodeManager(Conf.fattureInCloud.clientId, Conf.fattureInCloud.clientSecret, Conf.fattureInCloud.redirectUri);

export const authorize = (authToken: string) =>
    oauth
        .fetchToken(authToken)
        .then((tok) => {
            console.log('Received', tok, typeof tok);
            return {
                accessToken: tok.accessToken, // those values are undefined, I can use tok.access_token instead
                refreshToken: tok.refreshToken,
                accessExpiresIn: tok.expiresIn,
                refreshExpiresIn: 86400 * 365,
            };
        })
```

**Expected behavior**
fetchToken() should return a correct `OAuth2AuthorizationCodeTokenResponse`

**Comment by emajo** [comment]
Hi @belinde, thanks for reporting the issue, we fixed it and it will be in the next SDK release.

Thanks again,
Emanuele

**Comment by emajo** [comment]
Hi @belinde we just released the new version of the sdk that contains the fix you needed.

Thanks again,
Emanuele
