### ISSUE TITLE
Il client invia un payload invalido nell'endpoint "Send the e-invoice"

### ISSUE THREAD

**Issue by stefanoverna** [fattureincloud/fattureincloud-ts-sdk#19]
A partire da qualche giorno fa, il seguente metodo: 

```
await new IssuedEInvoicesApi(ficConfig).sendEInvoice(companyId, documentId);
```

Ritorna errore 422:

```
{
  "data": {
    "error": {
      "message": "Invalid JSON data in request body.",
      "validation_result": null
    }
  },
  "status": 422,
  "statusText": "Unprocessable Entity"
}
```

Il client invia come body della richiesta un oggetto JSON vuoto `{}`. Provando invece manualmente, senza client, ad effettuare la stessa chiamata API ma **senza payload**, l'endpoint ritorna 200 correttamente.

Riassumendo, questa ritorna 422 (ed è ciò che il client TS invia):

```
curl 'https://api-v2.fattureincloud.it/c/625291/issued_documents/240182230/e_invoice/send' -H 'Content-Type: application/json' -X POST -H 'Authorization: Bearer XXX' --data-raw '{}'

{"error":{"message":"Invalid JSON data in request body.","validation_result":null}}
```

Questa invece ritorna 200:

```
curl 'https://api-v2.fattureincloud.it/c/625291/issued_documents/240182230/e_invoice/send' -H 'Content-Type: application/json' -X POST -H 'Authorization: Bearer XXX'

{"data":{"name":"CARICATO","date":"2022-11-03 08:24:09"}}
```

Qualcosa deve essere cambiato lato API, perchè per mesi ha funzionato. In attesa di un fix ufficiale, vorrei sapere se è possibile forzare il client TS a non inviare alcun payload.

**Comment by stefanoverna** [comment]
Update, con questa chiamata non si lamenta:

```
await new IssuedEInvoicesApi(ficConfig).sendEInvoice(companyId, documentId, { data: {} });
```

ma è comunque un cambiamento di comportamento.

**Comment by emajo** [comment]
Ciao @stefanoverna, hai aggiornato la versione dell'sdk recentemente? Lato API non è stato cambiato nulla relativo a ciò.

**Comment by stefanoverna** [comment]
no, tutto rimasto invariato da mesi 😕

**Comment by giovantenne** [comment]
Confermo il problema. 
SDK bloccato alla versione 2.0.1 da mesi. Deve essere cambiato qualcosa lato API

**Comment by emajo** [comment]
Ciao @stefanoverna @giovantenne effettivamente era stata cambiata la validazione del json delle richieste, ora dovrebbe funzionare tutto come prima.
