### ISSUE TITLE
Transform proform invoice to e-invoice flow broken

### ISSUE THREAD

**Issue by destlaver** [fattureincloud/fattureincloud-ts-sdk#24]
It costed me an entire afternoon to address this issue, I post the solution here so you don't have to waste your time too:

when you call trasnformIssuedDocument it returns an object with two props: data and options.
then you pass the object to createIssuedDocument(company_id, object)

if it returns error 500 it's because options.from is an array: ['invoiceid'] instead of directly 'invoiceid'

**Comment by emajo** [comment]
Hi @destlaver, thank you for reporting this issue, we will fix it as soon as possible, the next time you have API related problems I suggest to open a discussion [here](https://github.com/fattureincloud/api/discussions).

Thanks,
Emanuele.
